---
title: "scRNAseq QC"
author: 
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: lumen
    fig_width: 5  # Adjust the width as needed
    fig_height: 6
---

Reference: [QC for scRNAseq Seurat Objects](https://satijalab.org/seurat/articles/pbmc3k_tutorial)



```{r init, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
Sys.setenv(PATH = paste(Sys.getenv("PATH"),
  "/opt/miniconda3/envs/seurat/bin",
  sep = ":"
))
Sys.setenv(R_LIBS_USER = "/opt/miniconda3/envs/seurat/lib/R/library")
Sys.setenv(RSTUDIO_PANDOC = "/opt/miniconda3/envs/seurat/bin/pandoc")
Sys.setenv(RENV_PATHS_ROOT = "/data/shared_env/renv/")

options(repos = BiocManager::repositories())
```


```{r, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
library(Seurat)
library(stringr)
library(ggplot2)
library(knitr)
library(gridExtra)
```

Currently only support 10x style output
#TODO: Support generic 3 tuble input(gene_names, barcodes, matrix.mt )
```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
# samples -> list.dirs("PROECCT_PROCESSING_PATH/results/cellranger/mtx_conversions/")

samples_dirs <- list.dirs(
  "/data/projects/240115_Jacobi_Schemionek_MedIV_scRNAseq/nfcore_scRNAseq/results/cellranger/mtx_conversions/",
  recursive = FALSE
)

valid_sample_dir <- c()
# make sure that each directory has the required inputs to the 10x pipeline
for (dir in samples_dirs) {
  dir_content <- list.files(dir, recursive = FALSE)

  components_present <- all(
    any(grepl("matrix.mtx", dir_content)),
    any(grepl("barcodes.tsv.gz", dir_content)),
    any(grepl("features.tsv.gz", dir_content))
  )
  valid_sample_dir <- c(valid_sample_dir, dir)
}
```

```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
INPUT_DIR <- "/data/projects/240115_Jacobi_Schemionek_MedIV_scRNAseq/nfcore_scRNAseq/results/cellranger/mtx_conversions//HD_CD34_Ctrl"
obj <- Read10X(INPUT_DIR)
```

```{r, echo=FALSE, results='hide', warning=FALSE, message=FALSE}
seurat_obj <- CreateSeuratObject(obj, min.cells = 3, min.features = 200, project = basename(INPUT_DIR))
seurat_obj[["percent.mito"]] <- PercentageFeatureSet(seurat_obj, pattern = "^MT-")
seurat_obj[["percent.ribo"]] <- PercentageFeatureSet(seurat_obj, pattern = "^RPS|^RPL")
```



```{r}
mad(seurat_obj@meta.data$percent.mito)
median(seurat_obj@meta.data$percent.mito)
```

```{r violin_plot, echo=FALSE, results='asis', warning=FALSE, message=FALSE, dpi=300, fig.width=8, fig.height=6, fig.format='png'}
VlnPlot(seurat_obj, features = c("nFeature_RNA", "nCount_RNA", "percent.mito", "percent.ribo"), ncol = 4)

```


```{r histograms, echo=FALSE, results='asis', warning=FALSE, message=FALSE, dpi=300, fig.width=8, fig.height=6, fig.format='png', }



histogram_seurat = function(obj, variable, n_mad = 3, vlines = FALSE, annotate = FALSE){
  
  
  no_breaks = 30
  
  vec = obj@meta.data[[variable]]
  mad_features = mad(vec)
  median_features = median(vec)
  upper = median_features + n_mad * mad_features
  lower = median_features - n_mad * mad_features
  
  upper_cells = sum(vec > upper)
  lower_cells = sum(vec < lower)
  inbetween = sum(lower < vec & vec < upper)

  info = hist(vec, breaks = no_breaks, plot =  FALSE)
  y_pos = mean(sort(info$counts, decreasing = TRUE)[1:3])

  
  
  fig = ggplot(obj@meta.data, aes_string(x = variable))+geom_histogram(color = "red3", fill = "red3")+
  theme_classic()
  if(vlines == TRUE){
  fig = fig + geom_vline(xintercept = upper, linetype = 2)+
  geom_vline(xintercept = lower, linetype = 2)
  }
    
  if (annotate == TRUE) {
    fig = fig +   annotate(geom = "text", label = upper_cells, x = (upper + max(info$breaks)) / 2, y = y_pos)+
  annotate(geom = "text", label = lower_cells, x = (lower + min(info$breaks)) / 2, y = y_pos)+
  annotate(geom = "text", label = inbetween, x =  mean(vec), y = y_pos * 1.1)+
  ylab("count")

  }
  
  return(fig)
  
}



p1 = histogram_seurat(seurat_obj, "nFeature_RNA", 3)
p2 = histogram_seurat(seurat_obj, "percent.mito", 3)
p3 = histogram_seurat(seurat_obj, "nCount_RNA", 3)
p4 = histogram_seurat(seurat_obj, "percent.ribo", 3)



(p1 + p2) / (p3 + p4)

```


```{r}
count = isOutlier(seurat_obj$nCount_RNA, nmads = 3, type = "both")
features =isOutlier(seurat_obj$nFeature_RNA, nmads = 3, type = "both")
mito = isOutlier(seurat_obj$percent.mito, nmads = 3, type = "both")

seurat_obj@meta.data$mito_outlier = mito
seurat_obj@meta.data$features_outlier = features
seurat_obj@meta.data$counts_outlier = count
seurat_obj@meta.data$outlier = (count | features | mito)


```



```{r scatter_plots, echo=FALSE, results='asis', warning=FALSE, message=FALSE, dpi=300, fig.width=10, fig.height=4, fig.format='png'}


plot1 = ggplot(as.data.frame(seurat_obj@meta.data), aes(x = nCount_RNA, y = percent.mito, color = mito_outlier))+
  geom_point( size = 1, alpha = 0.4)+
  theme_classic()+
  scale_color_brewer(palette = "Set2")

plot2 = ggplot(as.data.frame(seurat_obj@meta.data), aes(x = nCount_RNA, y = nFeature_RNA, color = outlier))+
  geom_point( size = 1, alpha = 0.4)+
  theme_classic()+
  scale_color_brewer(palette = "Set2")

plot1 + plot2


```

#Next:
Remove outliers, Normalize, Plot those figures again, PCA, UMAP
```{r scatter_plots_after_subsetting, echo=FALSE, results='asis', warning=FALSE, message=FALSE, dpi=300, fig.width=10, fig.height=4, fig.format='png'}
seurat_obj_subsetted = subset(seurat_obj, outlier == FALSE)

dim(seurat_obj_subsetted)
dim(seurat_obj)



p1 = histogram_seurat(seurat_obj_subsetted, "nFeature_RNA", 3)
p2 = histogram_seurat(seurat_obj_subsetted, "percent.mito", 3)
p3 = histogram_seurat(seurat_obj_subsetted, "nCount_RNA", 3)
p4 = histogram_seurat(seurat_obj_subsetted, "percent.ribo", 3)



(p1 + p2) / (p3 + p4)
```


```{r scatter_plots2_after_subsetting, echo=FALSE, results='asis', warning=FALSE, message=FALSE, dpi=300, fig.width=10, fig.height=4, fig.format='png'}
plot1 = ggplot(as.data.frame(seurat_obj_subsetted@meta.data), aes(x = nCount_RNA, y = percent.mito, color = mito_outlier))+
  geom_point( size = 1, alpha = 0.4)+
  theme_classic()+
  scale_color_brewer(palette = "Set2")



plot2 = ggplot(as.data.frame(seurat_obj_subsetted@meta.data), aes(x = nCount_RNA, y = nFeature_RNA, color = outlier))+
  geom_point( size = 1, alpha = 0.4)+
  theme_classic()+
  scale_color_brewer(palette = "Set2")

plot1 + plot2

```


```{r PCA, echo=FALSE, results='asis', warning=FALSE, message=FALSE, dpi=300, fig.width=10, fig.height=4, fig.format='png'}



```




