[project]
name = "Preprocessing"
version = "0.1.0"
description = "Module for pre-preprocessing of sc-RNA-seq datasets."
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge", "bioconda", "paul.martin-2", "pytorch"]
platforms = ["linux-64"]

[system-requirements]
linux = "4.12.14"

[dependencies]
scanpy = ">=1.10.1,<1.11"
ipykernel = ">=6.29.3,<6.30"
python = "3.11.*"
tomlkit = ">=0.12.5,<0.13"
pixi-kernel = ">=0.3.0,<0.4"
jupyterlab = ">=4.2.1,<4.3"
nbconvert = ">=7.16.4,<7.17"
igraph = "*"
leidenalg = ">=0.10.2,<0.11"
patchworklib = ">=0.6.3,<0.7"
plotnine = ">=0.13.6,<0.14"
scikit-image = ">=0.22.0,<0.23"
bioconductor-zellkonverter = ">=1.12.1,<1.13"
bioconductor-singlecellexperiment = ">=1.24.0,<1.25"
r-optparse = ">=1.7.5,<1.8"
r-irkernel = ">=1.3.2,<1.4"
r-biocmanager = ">=1.30.23,<1.31"
bioconductor-genomeinfodb = { version = "*", channel = "bioconda" }
bioconductor-decontx = { version = ">=1.0.0,<1.1", channel = "bioconda" }
session-info = ">=1.0.0,<1.1"
scikit-misc = { version = ">=0.1.4,<0.2", channel = "conda-forge" }
r-clustree = ">=0.5.1,<0.6"
ipywidgets = ">=8.1.3,<8.2"
r-curl = ">=5.1.0,<5.2"
r-tidyverse = ">=2.0.0,<2.1"
celltypist = ">=1.6.3,<1.7"
itables = ">=2.1.3,<2.2"
hvplot = ">=0.10.0,<0.11"
jupyter_bokeh = ">=4.0.5,<4.1"
plotly = ">=5.22.0,<5.23"
holoviews = ">=1.19.0,<1.20"
quarto = ">=1.4.550,<1.5"
kneed = ">=0.8.5,<0.9"
tqdm = ">=4.66.5,<5"

[pypi-dependencies]
kaleido = "*"
cellnet = { path = "./utils/cellnet" }
torch = ">=2.4.0, <3"
