[project]
name = "annotation_test"
version = "0.1.0"
description = "Add a short description here"
authors = ["= <=>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[system-requirements]
linux = "4.12.14"


[tasks]

[dependencies]
python = "3.10.*"
gcc_linux-64 = { version = "*" }
jupyterlab = ">=4.2.2,<4.3"
aiobotocore = "==2.3.3"
ipykernel = ">=6.29.4,<6.30"
tiledb = ">=2.24.0,<2.25"
numpy = "==1.26.4"
pixi-kernel = ">=0.3.0,<0.4"
faiss-gpu = ">=1.7.4,<1.8"


[pypi-dependencies]
scgpt = "*"
cellxgene-census = { version = "*", extras = ["experimental"] }
scanpy = ">=1.10.1,<1.11"
scvi-tools = "*"
