[project]
name = "cell-cell communication"
version = "0.1.0"
description = "Module for cell-cell communication."
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge", "bioconda", "paul.martin-2", "pytorch", "r"]
platforms = ["linux-64"]

[system-requirements]
linux = "4.12.14"

[dependencies]
scanpy = ">=1.10.1,<1.11"
ipykernel = ">=6.29.3,<6.30"
python = "3.11.*"
tomlkit = ">=0.12.5,<0.13"
pixi-kernel = ">=0.3.0,<0.4"
jupyterlab = ">=4.2.1,<4.3"
igraph = "*"
r-optparse = ">=1.7.5,<1.8"
r-irkernel = ">=1.3.2,<1.4"
r-biocmanager = ">=1.30.23,<1.31"
session-info = ">=1.0.0,<1.1"
ipywidgets = ">=8.1.3,<8.2"
r-curl = ">=5.1.0,<5.2"
r-tidyverse = ">=2.0.0,<2.1"
itables = ">=2.1.3,<2.2"
jupyter_bokeh = ">=4.0.5,<4.1"
quarto = ">=1.4.550,<1.5"
"bioconductor-org.hs.eg.db" = ">=3.18.0,<4"
"bioconductor-org.mm.eg.db" = ">=3.18.0,<4"
r-reshape2 = ">=1.4.4,<2"
r-rstatix = ">=0.7.2,<0.8"
r-stringr = ">=1.5.1,<2"
r-pals = ">=1.9,<2"
r-graphlayouts = ">=1.1.0,<2"
r-ggraph = ">=2.1.0,<3"
r-ggplot2 = ">=3.5.1,<4"
r-patchwork = ">=1.2.0,<2"
r-igraph = ">=2.0.3,<3"
r-rcolorbrewer = ">=1.1_3,<2"
r-boot = ">=1.3_30,<2"
r-rmarkdown = ">=2.27,<3"
r-scales = ">=1.3.0,<2"
r-oce = ">=1.8_2,<2"
r-ggalluvial = ">=0.12.5,<0.13"
r-dt = ">=0.33,<0.34"
r-htmltools = ">=0.5.8.1,<0.6"
r-factoextra = ">=1.0.7,<2"
r-colorblindness = ">=0.1.9,<0.2"
bioconductor-complexheatmap = ">=2.18.0,<3"
r-extrafont = ">=0.19,<0.20"
r-ggridges = ">=0.5.6,<0.6"
r-ggnewscale = ">=0.5.0,<0.6"
r-gtools = ">=3.9.5,<4"
r-ggsci = ">=3.2.0,<4"
r-assertthat = ">=0.2.1,<0.3"
r-qpdf = ">=1.3.3,<2"
"r-r.methodss3" = ">=1.8.2,<2"
r-devtools = ">=2.4.5,<3"
r-seurat = { version = "==4.4.0", channel = "conda-forge" }
r-seuratobject = "==4.1.4"
r-renv = ">=1.0.7,<2"
r-ape = ">=5.8,<6"
r-rspectra = ">=0.16_1,<0.17"
r-spam = ">=2.10_0,<3"
"r-futile.options" = ">=1.0.1,<2"
r-fastmatch = ">=1.1_4,<2"
r-snow = ">=0.4_4,<0.5"
r-tidytree = ">=0.4.6,<0.5"
r-downloader = ">=0.4,<0.5"
r-sna = ">=2.7_2,<3"
r-scatterpie = ">=0.2.3,<0.3"
"r-statnet.common" = ">=4.9.0,<5"
r-network = ">=1.18.2,<2"
r-gson = ">=0.1.0,<0.2"
"r-spatstat.univar" = ">=3.0_0,<4"
r-formatr = ">=1.14,<2"
"r-lambda.r" = ">=1.2.4,<2"
"r-futile.logger" = ">=1.4.3,<2"
r-shadowtext = ">=0.1.4,<0.2"
r-aplot = ">=0.2.3,<0.3"
r-chk = ">=0.9.2,<0.10"
r-fastdummies = ">=1.7.3,<2"
r-networkdynamic = ">=0.11.4,<0.12"
r-matchit = ">=4.5.5,<5"
r-rcpphnsw = ">=0.6.0,<0.7"
"bioconductor-go.db" = ">=3.18.0,<4"
bioconductor-treeio = ">=1.26.0,<2"
bioconductor-qvalue = ">=2.34.0,<3"
bioconductor-fgsea = ">=1.28.0,<2"
bioconductor-biocparallel = ">=1.36.0,<2"
"bioconductor-hdo.db" = ">=0.99.1,<0.100"
bioconductor-ggtree = ">=3.10.0,<4"
bioconductor-gosemsim = ">=2.28.0,<3"
bioconductor-dose = ">=3.28.1,<4"
bioconductor-enrichplot = ">=1.22.0,<2"
bioconductor-clusterprofiler = ">=4.10.0,<5"
bioconductor-genomeinfodbdata = ">=1.2.11,<2"

[pypi-dependencies]
liana = "*"
