[project]
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge", "bioconda", "nvidia", "pytorch"]
description = "Add a short description here"
name = "annotation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
sctab = "python utils/sctab_annotate.py"
scgpt = "python utils/scgpt_annotate.py"

[dependencies]
python = "3.9.*"
jupyterlab = ">=4.2.4,<5"
ipykernel = ">=6.29.5,<7"
pip = ">=24.2,<25"
tomlkit = ">=0.13.2,<0.14"
pixi-kernel = ">=0.4.0,<0.5"
scanpy = ">=1.10.2,<2"
pyarrow = ">=17.0.0,<18"
numpy = "1.*"
ipywidgets = ">=8.1.3,<9"
celltypist = "*"

[feature.scgpt]
pypi-dependencies = { scgpt = "*" }

[feature.scgpt.dependencies]
gcc_linux-64 = { version = "*" }
faiss-gpu = "*"
aiobotocore = "==2.3.3"
huggingface_hub = ">=0.24.5,<0.25"
pytorch = "2.*"


[feature.sctab.dependencies]
merlin-dataloader = { version = ">=23.8.0,<24", channel = "nvidia" }
merlin-core = { version = ">=23.8.0,<24", channel = "nvidia" }
lightning = ">=2.4.0,<3"
torchmetrics = ">=1.4.0.post0,<2"
tensorboard = ">=2.17.0,<3"
sparqlwrapper = ">=2.0.0,<3"
pytorch = "2.*"
huggingface_hub = ">=0.24.5,<0.25"


[pypi-dependencies]
session-info = "*"


[environments]
sctab = ["sctab"]
scgpt = ["scgpt"]
