[project]
name = "differential_expression"
version = "0.1.0"
description = "Add a short description here"
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
