[basic]
# ANALYSIS_DIR = "PROJECT_PROJECT_PATH/analysis"     # Default Analysis directory (provided by GPM)
# DIR_SAMPLES = "PROJECT_PROJECT_PATH/cellranger/*/outs/per_sample_outs" # CellRanger standard output or ParseBio
ANALYSIS_DIR = "."
DIR_SAMPLES = "../test"
DIR_SAVE = "save"       # Directory to save the results
TECHNOLOGY = "10x"      # values (10x, ParseBio)
ORGANISM = "human"      # values(human,  mouse)
TISSUE = "Blood"        # List: Tissue(s) of origin the samples, used later for annotation

auto_find = true # Automatically find the samples in the DIR_SAMPLES
samples = {}     # Override auto_find, provide a dictionary of {sample_name: sample_path} # Add samples names directly after '{' don't use a new line.

[normalization]
NORMALIZATION_METHOD = "log_norm" # Normalization method. values ('log_norm', 'p_residuals')
COUNTS_LAYER = "counts"           # Can be also 'decontXcounts' for decontaminated counts or  'X' for the adata.X matrix

[clustering]
FINAL_RESOLUTION = 1           # Float: Final resolution for clustering, Default: -1 (unset)
INTEGRATE_SAMPLES = false
INTEGRATION_METHOD = "harmony" # can be also 'MNN', 'seurat' or 'scVI', Not implemented yet

[annotation]
ANNOTATE_SAMPLES = false
ANNOTATION_METHOD = "scGPT" # values ('celltypist', 'scGPT', 'cxg_atlas'), use scVI and scGPT on GPU only for large datasets
