[basic]
ANALYSIS_DIR = "root_analysis_dir"
DIR_SAMPLES = "../test/Moazzen" # CellRanger standard output or ParseBio
DIR_SAVE = "save"
TECHNOLOGY = "10x"              #or ParseBio 
ORGANISM = "mouse"              #Also mouse

auto_find = true
samples = { WT = "../test/Moazzen/WT_E11_5/sample_filtered_feature_bc_matrix", KO = "../test/Moazzen/Mut_E11_5/sample_filtered_feature_bc_matrix" }

[QC]
CONCAT_SAMPLES = true
NMADS = 5
NMADS_MITO = 3
CORRECT_AMBIENT_RNA = true
FILTER_DOUBLETS = true
CELL_CYCLE_SCORE = true
REGRESS = false
VARS_TO_REGRESS = []       # Add variables to regress pct_counts_mt, pct_counts_ribo


[Normalization]
NORMALIZATION_METHOD = "log1p" #also PearsonResidual

#Can be be a fraction between 0.0 and 1.0 or a number of genes
VARIABLE_FEATURES = 0.1 #Select top 10% of variable genes


[clustering]
CLUSTERING_RANGE = [0.1, 3]

