[project]
name = "scanpy_pipeline"
version = "0.1.0"
description = "Add a short description here"
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tasks]

[dependencies]
scanpy = ">=1.10.1,<1.11"
numpy = ">=1.26.4,<1.27"
anndata = ">=0.10.7,<0.11"
r-reticulate = ">=1.37.0,<1.38"
r-rmarkdown = ">=2.27,<3"
r-essentials = { version = ">=4.3,<5", channel = "conda-forge" }
r-base = { version = ">=4.3.3,<4.4", channel = "conda-forge" }
quarto = ">=1.4.550,<1.5"
pooch = ">=1.8.1,<1.9"
toml = { version = ">=0.10.2,<0.11", channel = "conda-forge" }
anndata2ri = { version = ">=1.3.1,<1.4", channel = "bioconda" }
igraph = ">=0.10.12,<0.11"
