[project]
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge", "nvidia", "pytorch"]
description = "Add a short description here"
name = "scTab"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.9.*"
pyarrow = ">=17.0.0,<18"
merlin-dataloader = { version = ">=23.8.0,<24", channel = "nvidia" }
merlin-core = { version = ">=23.8.0,<24", channel = "nvidia" }
numpy = "1.*"
pandas = "1.*"
lightning = ">=2.4.0,<3"
torchmetrics = ">=1.4.0.post0,<2"
tensorboard = ">=2.17.0,<3"
scipy = ">=1.13.1,<2"
sparqlwrapper = ">=2.0.0,<3"
pytorch = "2.*"
scanpy = ">=1.10.2,<2"
pixi-kernel = ">=0.4.0,<0.5"
ipykernel = ">=6.29.5,<7"
pip = ">=24.2,<25"
tomlkit = ">=0.13.0,<0.14"
huggingface_hub = ">=0.24.5,<0.25"
ipywidgets = ">=8.1.3,<9"

[pypi-dependencies]
session-info = "*"
