```{r init, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
source("/etc/rstudio/Rprofile.site")
library(plotly)
library(heatmaply)
library(dplyr)
library(DT)
library(ggplot2)
library(DESeq2)
library(tximport)
library(readr)
library(tximportData)
library(stringr)
library(tidyr)
library(data.table)
library(openxlsx)
library(AnnotationDbi, warn.conflicts = FALSE)

heading_for_report <- c()
```

```{r setting, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
# Define controllers
generate_Rmd <- TRUE
render_html <- TRUE
# Paths
DIR_base <- "PROJECT_PROJECT_PATH/"
DIR_analysis <- paste0(DIR_base, "analysis/")
DIR_DGEA <- paste0(DIR_analysis, "DEA_miRNA/")
setwd(DIR_DGEA)
FILE_counts_mature <- paste0(DIR_base, "nfcore_miRNAseq/results/mirna_quant/edger_qc/mature_counts.csv")
FILE_counts_hairpin <- paste0(DIR_base, "nfcore_miRNAseq/results/mirna_quant/edger_qc/hairpin_counts.csv")

# Load functions
source(paste0(DIR_DGEA, "DEA_miRNA_functions.R"))

# Organism
organism <- "PROJECT_PROCESSING_ORGANISM" # hsapiens mmusculus rnorvegicus sscrofa
# Parameters
Fig_width <- 600
Fig_height <- 400
CUTOFF_Quantification <- 20
CUTOFF_ADJP <- 0.05
spikein_ERCC <- FALSE
save(DIR_base, DIR_analysis, DIR_DGEA, FILE_counts_mature, FILE_counts_hairpin, 
     organism, spikein_ERCC,
     Fig_width, Fig_height, CUTOFF_Quantification, CUTOFF_ADJP,
     file = "DEA_miRNA_settings.RData")
```

```{r samples, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
# if samplesheet.csv is not under analysis/, please do this:
# cut -d ',' -f 1 ../nfcore_miRNAseq/samplesheet.csv | awk 'BEGIN{FS=OFS="_"} {print $0, $1, $2, $3, $4}' OFS=',' > samplesheet.csv
# Loading samples
samples <- read.csv("../samplesheet.csv")
rownames(samples) <- samples$sample
samples
```


```{r All_samples, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
filetag <- "All_samples"
description <- str_replace_all(filetag, "_", " ")
filtered_samples <- samples
# filtered_samples$group <- factor(filtered_samples$group, levels = c("Placebo","Treatment"))
# colnames(filtered_samples) <- c("sample","time","group","batch","tube")
if ( generate_Rmd == TRUE ) {
  add_DGEA(description=description, 
           tag=filetag, 
           filtered_samples=filtered_samples, 
           paired=FALSE,
           volcano=FALSE, maplot=FALSE, sigtable=FALSE)
}
if ( render_html == TRUE ) {
  rmarkdown::render(paste0('DEA_miRNA_',filetag,'.Rmd'), 
                    output_format = 'html_document',
                    output_file = paste0('DEA_miRNA_',filetag,'.html'))
}
heading_for_report <- c(heading_for_report, paste0("### [",description,"](DEA_miRNA/DEA_miRNA_",filetag,".html)"))
```

```{r, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
filetag <- "Subtype_Treatment_vs_Control"
description <- str_replace_all(filetag, "_", " ")
filtered_samples <- samples[samples$group=="Subtype",]
filtered_samples$time <- factor(filtered_samples$time, levels = c("Control","Treatment"))
colnames(filtered_samples) <- c("sample","group","treatment","batch","tube")
if ( generate_Rmd == TRUE ) {
  add_DGEA(description=description, 
           tag=filetag, 
           filtered_samples=filtered_samples, 
           paired=TRUE,
           volcano=TRUE, maplot=TRUE, sigtable=TRUE)
}
if ( render_html == TRUE ) {
  rmarkdown::render(paste0('DEA_miRNA_',filetag,'.Rmd'), 
                    output_format = 'html_document',
                    output_file = paste0('DEA_miRNA_',filetag,'.html'))
}
heading_for_report <- c(heading_for_report, paste0("### [",description,"](DEA_miRNA/DEA_miRNA_",filetag,".html)"))
```


```{r, echo=FALSE, results='markup', warning=FALSE, message=TRUE}
cat(heading_for_report, sep = "\n")
```