[project]
name = "template"
version = "0.1.0"
description = "Add a short description here"
authors = ["Joseph Kuo <chao-chung.kuo@rwth-aachen.de>"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
tomlkit = ">=0.12.5,<0.13"
numpy = ">=2.0.0,<2.1"
matplotlib = ">=3.8.4,<3.9"
pandas = ">=2.2.2,<2.3"
itables = ">=2.1.3,<2.2"
seaborn = ">=0.13.2,<0.14"
ipykernel = ">=6.29.4,<6.30"
scanpy = ">=1.10.2,<1.11"
ipywidgets = ">=8.1.3,<8.2"
yaml = ">=0.2.5,<0.3"
quarto = ">=1.4.550,<1.5"
pyyaml = ">=6.0.1,<6.1"
nbformat = ">=5.10.4,<5.11"
nbclient = ">=0.10.0,<0.11"
