```{r init, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
source("/etc/rstudio/Rprofile.site")
library(heatmaply)
library(dplyr)
library(DT)
library(ggplot2)
library(DESeq2)
library(tximport)
library(readr)
library(tximportData)
library(stringr)
library(tidyr)
library(data.table)
library(openxlsx)
library(AnnotationDbi, warn.conflicts = FALSE)

heading_for_report <- c()
```

```{r setting, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
# Define controllers
generate_Rmd <- TRUE
render_html <- TRUE
render_3DPCA <- FALSE
# Paths
DIR_base <- "PROJECT_PROJECT_PATH/"
DIR_analysis <- paste0(DIR_base, "analysis/")
DIR_DGEA <- paste0(DIR_analysis, "DGEA/")
setwd(DIR_DGEA)
DIR_salmon <- paste0(DIR_base, "PROJECT_PROCESSING_METHOD/results/star_salmon/")
FILE_tx2gene <- paste0(DIR_base, "PROJECT_PROCESSING_METHOD/results/star_salmon/tx2gene.tsv")
# FILE_salmon_ct <- paste0(DIR_salmon, "salmon.merged.gene_counts_scaled.tsv") # 3mRNAseq
FILE_salmon_ct <- paste0(DIR_salmon, "salmon.merged.gene_counts_length_scaled.tsv") # RNAseq
# Load functions
source(paste0(DIR_DGEA, "DGEA_RNAseq_functions.R"))
# DESeq2
countsFromAbundance <- "lengthScaledTPM" # no for 3mRNAseq, lengthScaledTPM for others
lengthcorrection <- TRUE # FALSE for 3mRNAseq, TRUE for others
norm_spikein_ERCC <- FALSE
# Organism
organism <- "PROJECT_PROCESSING_ORGANISM" # hsapiens mmusculus rnorvegicus sscrofa
# Parameters
Fig_width <- 600
Fig_height <- 400
CUTOFF_Quantification <- 20
CUTOFF_ADJP <- 0.05
save(DIR_base, DIR_analysis, DIR_DGEA, DIR_salmon, FILE_tx2gene, FILE_salmon_ct,
     countsFromAbundance, lengthcorrection, norm_spikein_ERCC,
     organism, 
     Fig_width, Fig_height, CUTOFF_Quantification, CUTOFF_ADJP,
     file = "DGEA_settings.RData")
```

```{r samples, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
# Loading samples
samples <- read.csv("../samplesheet.csv")
rownames(samples) <- samples$sample
samples
```

```{r All_samples, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
filetag <- "All_samples"
description <- str_replace_all(filetag, "_", " ")
filtered_samples <- samples
filtered_samples$group <- factor(filtered_samples$group, levels = c("Placebo","Treatment"))
colnames(filtered_samples) <- c("sample","time","group","batch","tube")
if ( generate_Rmd == TRUE ) {
  add_DGEA(description=description, 
           tag=filetag, 
           filtered_samples=filtered_samples, 
           paired=FALSE,
           volcano=FALSE, maplot=FALSE, sigtable=FALSE)
}
if ( render_html == TRUE ) {
  rmarkdown::render(paste0('DGEA_',filetag,'.Rmd'), 
                    output_format = 'html_document',
                    output_file = paste0('DGEA_',filetag,'.html'))
}
heading_for_report <- c(heading_for_report, paste0("### [",description,"](DGEA/DGEA_",filetag,".html)"))
```

```{r, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
description <- "Treatment vs Control"
filetag <- str_replace_all(description, " ", "_")
description_parts <- strsplit(description, " ")[[1]]
filtered_samples <- samples
filtered_samples$group <- factor(filtered_samples$group, levels = c(description_parts[3], description_parts[1]))
filtered_samples <- filtered_samples[complete.cases(filtered_samples$group), ]
if ( generate_Rmd == TRUE ) {
  add_DGEA(description=description, 
           tag=filetag, 
           filtered_samples=filtered_samples, 
           paired=TRUE,
           volcano=TRUE, maplot=TRUE, sigtable=TRUE)
}
if ( render_html == TRUE ) {
  rmarkdown::render(paste0('DGEA_',filetag,'.Rmd'), 
                    output_format = 'html_document',
                    output_file = paste0('DGEA_',filetag,'.html'))
}
heading_for_report <- c(heading_for_report, paste0("### [",description,"](DGEA/DGEA_",filetag,".html)"))
```

# SimpleComparison is used when there is no duplicate samples
# ```{r, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
# description <- "Treatment vs Control"
# filetag <- str_replace_all(description, " ", "_")
# description_parts <- strsplit(description, " ")[[1]]
# filtered_samples <- samples
# filtered_samples$group <- factor(filtered_samples$group, levels = c(description_parts[3], description_parts[1]))
# filtered_samples <- filtered_samples[complete.cases(filtered_samples$group), ]
# if ( generate_Rmd == TRUE ) {
#   add_SimpleComparison(salmon_count_table=FILE_salmon_ct, 
#                        group_base=description_parts[3], 
#                        group_com=description_parts[1])
# }
# if ( render_html == TRUE ) {
#   rmarkdown::render(paste0('SimpleComparison_',filetag,'.Rmd'), 
#                     output_format = 'html_document',
#                     output_file = paste0('SimpleComparison_',filetag,'.html'))
# }
# heading_for_report <- c(heading_for_report, paste0("### [",description,"](DGEA/SimpleComparison_",filetag,".html)"))
# ```

```{r, echo=FALSE, results='markup', warning=FALSE, message=TRUE}
cat(heading_for_report, sep = "\n")
```