---
title: "DGEA Geneset Comparisons"
author:
PROJECT_AUTHORS
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: lumen
bibliography: ../references.bib
---

```{r, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
source("/etc/rstudio/Rprofile.site")
options(repos = BiocManager::repositories())

library(data.table)
library(ggplot2)
library(ggpubr)
library(ggVennDiagram)
library(openxlsx)
library(DT)

CUTOFF_ADJP <- 0.05
CUTOFF_FC <- 1
COUNTER <- 0 # Counter to avoid the colliding of chunk names

Tag_this_analysis <- "DGEA_Geneset_Comparisons"

extract_de_genes <- function(filename, direction = FALSE) {
  degenes <- fread(filename)[, c("gene_symbol", "log2FoldChange", "padj")]
  if (direction == "up") {
    degenes <- degenes[degenes$log2FoldChange >= CUTOFF_FC]
  } else if (direction == "down") {
    degenes <- degenes[degenes$log2FoldChange <= CUTOFF_FC * -1]
  }
  return(unique(unlist(degenes$gene_symbol[degenes$padj < CUTOFF_ADJP])))
}
venn_diagram <- function(gene_sets, title) {
  ggVennDiagram(gene_sets, edge_size = 0.5, label_size = 2) +
  coord_fixed(clip = "off") +
  scale_fill_gradient(low = "grey", high = "firebrick") +
  # scale_x_continuous(expand = expansion(mult = 0.3)) +  # Add extra space around X
  # scale_y_continuous(expand = expansion(mult = 0.3)) +  # Add extra space around Y
  theme(
    plot.margin = margin(t = 20, r = 30, b = 20, l = 30)  # Top, right, bottom, left margins (in 'pt')
  ) +
  ggtitle(title)
}
venn_table <- function(table_name, gene_sets) {
  # table_name <- paste0(Tag_this_analysis, "_All_DE_genes.xlsx")
  venn_data <- ggVennDiagram::process_data(Venn(gene_sets))
  region_info <- venn_region(venn_data)
  write.xlsx(region_info, file = table_name, asTable = TRUE)
  region_info$item <- sapply(region_info$item, function(x) paste(x, collapse = ","))
  datatable(
    region_info, 
    plugins = "ellipsis",
    options = list(
      columnDefs = list(list(
        targets = c(2,3),
        render = JS("$.fn.dataTable.render.ellipsis( 30, false )")
      ))
    )
  )
}
```

# All DE genes {.tabset}

## Venn Diagram

```{r, echo=TRUE, results="asis", warning=FALSE, message=FALSE, dpi=600, fig.width=6, fig.height=4}
gene_sets <- list(
  # Generation1 = extract_de_genes("DGEA_Generation1_vs_WT_stat.csv"),
  Generation2 = extract_de_genes("DGEA_Generation2_vs_WT_stat.csv"),
  Generation3 = extract_de_genes("DGEA_Generation3_vs_WT_stat.csv"),
  Generation4 = extract_de_genes("DGEA_Generation4_vs_WT_stat.csv"),
  Gender = extract_de_genes("DGEA_Female_vs_Male_stat.csv")
)
venn_diagram(gene_sets,
             "Overlap of Genes Across Conditions")
```

## Table

```{r, echo=TRUE, warning=FALSE, message=FALSE}
table_name <- paste0(Tag_this_analysis, "_All_DE_genes.xlsx")
venn_table(table_name, gene_sets)
```

Download the full list [`r table_name`](`r table_name`).


# R session information

```{r, echo=FALSE, results='markup', warning=FALSE, message=TRUE}
sessionInfo()
```
