default:
  spikein_ERCC: FALSE  # Choose either TRUE or FALSE
  organism: "hsapiens"  # Choose one of "hsapiens", "mmusculus", or "rnorvegicus"
  countsFromAbundance: "no"
  lengthcorrection: FALSE
  
RNAseq:
  countsFromAbundance: "lengthScaledTPM"
  lengthcorrection: TRUE

totalRNAseq:
  countsFromAbundance: "lengthScaledTPM"
  lengthcorrection: TRUE

mRNAseq:
  countsFromAbundance: "lengthScaledTPM"
  lengthcorrection: TRUE

3mRNAseq:
  countsFromAbundance: "no"
  lengthcorrection: FALSE
