---
title: "DGEA Integrated Heatmap"
author:
PROJECT_AUTHORS
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: false
    theme: lumen
---

```{r, echo=FALSE, results="hide", warning=FALSE, message=FALSE}
source("/etc/rstudio/Rprofile.site")
library(data.table)
require(dplyr)
library(gtools)
library(stringr)
library(readxl)
require(DT)
library(ggplot2)
library(ggpubr)
library(pheatmap)
library(tidyr)
library(tibble)
options(warn = -1)

Tag_this_analysis <- "DGEA_heatmap"
# Define the significance threshold
padj_threshold <- 0.05
norm_count <- fread("DGEA_All_samples_norm_counts.csv")
stat_files <- list.files(path = ".", pattern = "DGEA_.*_stat\\.csv$", full.names = TRUE)
stat_files <- stat_files[-1]
filter_genes <- function(stat_files, topN) {
  filtered_genes <- list()
  # Loop through each file
  for (stat_file in stat_files) {
    # print(stat_file)
    # Read the CSV file
    data <- fread(stat_file, stringsAsFactors = FALSE)
    if (is.na(topN)) {
      sel_data <- data[data$padj < padj_threshold, ]
    } else {
      sel_data <- data[order(data$padj, decreasing = FALSE), ][1:topN, ]
    }
    # Store only the gene symbols as a character vector
    filtered_genes[[stat_file]] <- sel_data$gene_symbol
  }
  return(filtered_genes)
}
generate_hp <- function(target_genes, main, show_rownames, fontsize_row) {
  data_matrix <- as.data.frame(norm_count[norm_count$gene_name %in% target_genes,])
  rownames(data_matrix) <- make.unique(data_matrix$gene_name)
  data_matrix <- as.matrix(data_matrix[,c(-1,-2,-3)])
  data_matrix <- log10(data_matrix + 1)
  
  # Identify WT columns
  wt_cols <- grep("^WT", colnames(data_matrix), value = TRUE)
  # Identify other columns
  other_cols <- setdiff(colnames(data_matrix), wt_cols)
  # Reorder the data_matrix
  data_matrix <- data_matrix[, c(wt_cols, other_cols)]
  
  # Extract group from column names (everything before first underscore)
  group <- str_extract(colnames(data_matrix), "^[^_]+")
  group <- factor(group, levels = c("WT", sort(unique(group[group != "WT"]))))  # Put WT first
  
  # Create annotation data frame
  col_annotations <- data.frame(
    Group = group,
    row.names = colnames(data_matrix)
  )
  
  # Define custom colors for each group
  group_levels <- levels(group)
  group_colors <- setNames(RColorBrewer::brewer.pal(n = length(group_levels), name = "Set3"), group_levels)
  
  annotation_colors <- list(
    Group = group_colors
  )
  
  # Draw heatmap
  pheatmap(
    mat = data_matrix,
    cluster_rows = TRUE,
    cluster_cols = FALSE,
    clustering_distance_rows = "euclidean",
    clustering_distance_cols = "manhattan",
    clustering_method = "complete",
    scale = "none",
    fontsize = 7,
    fontsize_row = fontsize_row,
    fontsize_col = 2,
    show_rownames = show_rownames,
    show_colnames = TRUE,
    legend = TRUE,
    border_color = NA,
    angle_col = 45,
    main = main,
    annotation_col = col_annotations,
    annotation_colors = annotation_colors
  )
}
```

### [Back to the main page](../Analysis_Report_RNAseq.html)

# Combining all DE genes

```{r, echo=FALSE, results="asis", warning=FALSE, message=FALSE, dpi=600, fig.width=6, fig.height=8}
filtered_genes <- filter_genes(stat_files, topN=NA)
combined_genes <- unique(unlist(filtered_genes))
generate_hp(combined_genes, fontsize_row=2,
            main="All DE Genes", show_rownames=FALSE)
```

# Top 100 DE genes

```{r, echo=FALSE, results="asis", warning=FALSE, message=FALSE, dpi=600, fig.width=6, fig.height=8}
filtered_genes <- filter_genes(stat_files, topN=100)
combined_genes <- unique(unlist(filtered_genes))
generate_hp(combined_genes, fontsize_row=2,
            main="Top 100 DE genes", show_rownames=FALSE)
```

# Top 10 DE genes

```{r, echo=FALSE, results="asis", warning=FALSE, message=FALSE, dpi=600, fig.width=6, fig.height=5}
filtered_genes <- filter_genes(stat_files, topN=10)
combined_genes <- unique(unlist(filtered_genes))
generate_hp(combined_genes, fontsize_row=4,
            main="Top 10 DE genes", show_rownames=TRUE)
```

# Top DE genes in Generation2 vs WT

```{r, echo=FALSE, results="asis", warning=FALSE, message=FALSE, dpi=600, fig.width=6, fig.height=4}
filtered_genes <- filter_genes(stat_files, topN=20)
target_genes <- filtered_genes$`./DGEA_Generation2_vs_WT_stat.csv`
generate_hp(target_genes, fontsize_row=4,
            main="Top 20 DE genes in Generation2 vs WT", show_rownames=TRUE)
```

# GSEA

```{r, echo=FALSE, results="asis", warning=FALSE, message=FALSE}

xlsx_files <- list.files(path = ".", pattern = "DGEA_.*vs.*_export\\.xlsx$", full.names = TRUE)
# Initialize an empty list to store data from all files
gsea_list <- list()

# Iterate over each file
for (file in xlsx_files) {
  # Read the "GSEA_Results" sheet
  df <- read_excel(file, sheet = "GSEA_Results")
  
  # Select relevant columns and transform p.adjust into -log10(p.adjust)
  df <- df %>%
    select(Description, p.adjust) %>%
    mutate(p.adjust = -log10(p.adjust))  # Transform to -log10 scale
  
  # Store in list with filename as key
  gsea_list[[file]] <- df
}

# Combine all data into a single dataframe
gsea_combined <- bind_rows(gsea_list, .id = "File")

# Extract just the filename (remove path and extension)
gsea_combined$File <- gsub(".*/|\\.xlsx$", "", gsea_combined$File)
gsea_combined$File <- gsub("_export", "", gsea_combined$File)
gsea_combined$File <- gsub("DGEA_", "", gsea_combined$File)
# Reshape into wide format: GO Description as rows, File names as columns
gsea_matrix <- gsea_combined %>%
  pivot_wider(names_from = File, values_from = p.adjust, values_fill = 1)  # Fill missing values with 0

# Convert Description to row names and remove the column
gsea_matrix <- gsea_matrix %>% column_to_rownames(var = "Description")
colnames(gsea_matrix) <- gsub("_", " ", colnames(gsea_matrix))
gsea_matrix <- gsea_matrix[, mixedsort(colnames(gsea_matrix))]
```

```{r, echo=FALSE, results="asis", warning=FALSE, message=FALSE, dpi=600, fig.width=6, fig.height=8}
gsea_matrix_filtered <- gsea_matrix %>% 
  filter(if_any(everything(), ~ . > 7))
pheatmap(
  mat = gsea_matrix_filtered,               # Data matrix
  cluster_rows = TRUE,             # Cluster rows (genes)
  cluster_cols = FALSE,             # Cluster columns (samples)
  # clustering_distance_rows = "euclidean",  # Distance metric for rows
  # clustering_distance_cols = "manhattan",  # Distance metric for columns
  clustering_method = "complete",  # Clustering method (hierarchical clustering)
  fontsize = 7,                # Font size for text
  fontsize_row = 3,            # Font size for row labels
  fontsize_col = 5,            # Font size for column labels
  show_rownames = TRUE,         # Show gene names
  show_colnames = TRUE,         # Show sample names
  legend = TRUE,                # Show color legend
  border_color = "NA",       # Border color for heatmap cells
  angle_col = 45,               # Rotate column labels
  main = "Integrated GSEA p.adjust"  # Title of the heatmap
  # Add column annotations
  # annotation_col = col_annotations,  
  # annotation_colors = annotation_colors
)
```


# R session information

```{r, echo=FALSE, results='markup', warning=FALSE, message=TRUE}
sessionInfo()
```