[project]
name = "differential_expression"
version = "0.1.0"
description = "Add a short description here"
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["conda-forge", "bioconda", "pytorch"]
platforms = ["linux-64"]


[system-requirements]
linux = "4.12.14"


[tasks]


[dependencies]
python = "3.9.*"
numpy = "1.25"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.3,<9"
scanpy = ">=1.10.2,<2"
pegasuspy = ">=1.10.0,<2"
tomlkit = ">=0.13.2,<0.14"
decoupler-py = ">=1.8.0,<2"
openpyxl = ">=3.1.5,<4"
itables = ">=2.1.4,<3"
jupyterlab = ">=4.2.5,<5"
pixi-kernel = ">=0.4.0,<0.5"
panel = ">=1.4.5,<2"
jupyter_bokeh = ">=4.0.5,<5"
gseapy = ">=1.1.3,<2"
pooch = ">=1.8.2,<2"
quarto = ">=1.5.55,<2"
